env:
  browser: true
  node: true
  commonjs: true
  es2021: true

extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules: 
  no-prototype-builtins: 0 #should I leave it??