name: my-check

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: make install
      
      - name: Tests
        run: make test

      - name: Linter
        run: make lint
      
      - name: Test & publish code coverage
        # Publish code coverage on Code Climate
        # https://github.com/paambaati/codeclimate-action
        uses: paambaati/codeclimate-action@v2.7.4
        # Add Code Climate secret key
        env:
          CC_TEST_REPORTER_ID: c1e3e306ca74e45f11470dc4834481b1649221ce916c616094edaa1c791c097b
        with:
          coverageCommand: make test