name: my-check

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Show directory
        run: pwd

      - name: Show content
        run: ls -al

      - name: Install
        run: make install
      
      - name: Run tests
        run: make test